objective: # Choose loss type
  - Nonnegative Matrix Factorization[share_init=True]
dataset: # dataset to run benchmark on
  - simulated
solver: # list of example solvers to do benchmark
  - mu 
  - mu_berg
  - fpa
  - admm
  - sn 
  - ccd

# note: use more repetitions to have quantiles on the plot
n-repetitions: 10
timeout: 1s
max-runs: 10000