objective: # Choose loss type
  - Nonnegative Matrix Factorization[share_init=True]
dataset: # dataset to run benchmark on
  - simulated
solver: # list of example solvers to do benchmark
  - sklearn[loss=frobenius]
  # - nimfa
  - tensorly[strategy=HALS] #MU takes forever
  - apg

# note: use more repetitions to have quantiles on the plot
n-repetitions: 1